[workspace]
resolver = "2"
members = [
    "crates/parang",
    "crates/parang-cli",
]
default-members = ["crates/parang-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75"
authors = ["Wonsup Lee <onesup.lee@gmail.com>"]

[workspace.dependencies]
lopdf = { package = "lopdf-parang", version = "0.39.1", path = "lopdf" }
rayon = "1.10"
memmap2 = "0.9"
compact_str = "0.8"
encoding_rs = "0.8"
hashbrown = "0.15"
unicode-normalization = "0.1"
unicode-bidi = "0.3"
thiserror = "2"
log = "0.4"
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
mimalloc = "0.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
