[package]
name = "parang-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "CLI tool for PDF text extraction"

[[bin]]
name = "parang"
path = "src/main.rs"

[dependencies]
parang = { path = "../parang" }
clap = { workspace = true }
rayon = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
